#!/usr/bin/env python
# -*- coding: utf-8 -*-

import time, string, sys
import itertools, hashlib

NAME        = 'Python Crazy Decrypter'
VERSION     = '0.0.4'
AUTHOR      = 'Summon Agus'
DESCRIPTION = NAME + ''' is real crazy tool
to decrypt md5, sha1, sha224, sha256, sha384, and sha512 with Brute Force method.'''

CHRS = string.printable.replace(' \t\n\r\x0b\x0c', '')
DICT_MODULE_TYPES = {
    'md5'     : 32,
    'sha1'    : 40,
    'sha224'  : 56,
    'sha256'  : 64,
    'sha384'  : 96,
    'sha512'  : 128
}

def print_help():
    print '\n'+NAME
    print 'Author  : {}'.format(AUTHOR)
    print 'Version : {}\n'.format(VERSION)
    print DESCRIPTION
    print '''\nPARAMETERS:
    -m  \t To try with specific module choice.
    -a  \t To try with all modules.
    -c  \t To try with specific charachters.
    -ac \t To try with all charachters. \n\nUSAGE:
    SPECIFIC MODULE
     $ crazy_decrypter -m <module_type> <hashed> -c <chars> <min_length> <max_length>
     $ crazy_decrypter -m md5 d73d1e93a306b8230410cbe496ec84bf -c ABC 1 2

     $ crazy_decrypter -m <module_type> <hashed> -ac <min_length> <max_length>
     $ crazy_decrypter -m md5 d73d1e93a306b8230410cbe496ec84bf -ac 1 2

    ALL MODULES
     $ crazy_decrypter -a <hashed> -c <chars> <min_length> <max_length>
     $ crazy_decrypter -a d73d1e93a306b8230410cbe496ec84bf -c ABC 1 2

     $ crazy_decrypter -a <hashed> -ac <min_length> <max_length>
     $ crazy_decrypter -a d73d1e93a306b8230410cbe496ec84bf -ac 1 2
    '''

def decrypter(choice, module_type, hashed, chrs, min_length, max_length):
    if module_type in DICT_MODULE_TYPES.keys():
        improt_module = getattr(hashlib, '{}'.format(module_type))
    else:
        print '\n The `{}` does not exist in the list module!\n Please try this: {}\n'.format(module_type, DICT_MODULE_TYPES.keys())
        sys.exit()
    if min_length > max_length:
        print '\n Min-length must be longer than Max-length or as same as with Max-length.\n'
        sys.exit()
    if len(hashed) not in DICT_MODULE_TYPES.values():
        print "\n Provided hash doesn't match any of known hashes bitmap."
        print " Correct length for hases type:"
        for k, i in sorted(DICT_MODULE_TYPES.iteritems()):
            print ' -', k,':',i
        print ''
        sys.exit()
    if choice == '-m' and len(hashed) != DICT_MODULE_TYPES[module_type]:
        print "\n The hash `{}` is doesn't exist in `{}`.\n Please try another type!\n".format(hashed, module_type)
        sys.exit()

    end_result_chip = ''

    try:
        for n in range(min_length, max_length+1):
            for xs in itertools.product(chrs, repeat=n):
                result_chip = ''.join(xs)
                hash_chip = improt_module(result_chip).hexdigest()
                if hashed == hash_chip:
                    end_result_chip += result_chip
                    print 'Decrypt found : {}'.format(end_result_chip)
                    print 'Type Decrypt  : {}'.format(module_type)
                    print 'End time      : {}\n'.format(time.strftime('%H:%M:%S'))
                    sys.exit()
                else:
                    print '   *** Please drink your coffee first! ***'
                    print '\t{} {}\n'.format(NAME, VERSION)
                    print 'CTRL+C to Exit!'
                    print 'Charachters to try : {}'.format(chrs)
                    print 'Min-length         : {}'.format(min_length)
                    print 'Max-length         : {}'.format(max_length)
                    if choice == '-a':
                        print 'Type Decrypt found : {}'.format(module_type)
                    else:
                        print 'Type Decrypt now   : {}'.format(module_type)
                    print 'Trying with        : {} - {}'.format(result_chip, hash_chip)
                    time.sleep(0.01)
                    print("\033c")
    except KeyboardInterrupt:
        print 'Finished!\n'
        sys.exit()

    if end_result_chip == '':
        print 'Not Found!'
        print 'End time: {}\n'.format(time.strftime('%H:%M:%S'))
        sys.exit()
    else: pass

if __name__ == '__main__':
    if len(sys.argv) == 1 or len(sys.argv) > 8: print_help()
    elif sys.argv[1] == '-m':
        try:
            if sys.argv[4] == '-c':
                decrypter(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[5], int(sys.argv[6]), int(sys.argv[7]))
            elif sys.argv[4] == '-ac':
                decrypter(sys.argv[1], sys.argv[2], sys.argv[3], CHRS, int(sys.argv[5]), int(sys.argv[6]))
            else: print_help()
        except IndexError: print_help()
    elif sys.argv[1] == '-a':
        try:
            len_hases = len(sys.argv[2])
            module_type = DICT_MODULE_TYPES.keys()[DICT_MODULE_TYPES.values().index(len_hases)]
            if sys.argv[3] == '-c':
                decrypter(sys.argv[1], module_type, sys.argv[2], sys.argv[4], int(sys.argv[5]), int(sys.argv[6]))
            elif sys.argv[3] == '-ac':
                decrypter(sys.argv[1], module_type, sys.argv[2], CHRS, int(sys.argv[4]), int(sys.argv[5]))
            else: print_help()
        except IndexError: print_help()
    else: print_help()